const CHAP_SCRIPT = [
  '<script>',
  'function hexMD5(s){function L(a,b){return(a&65535)+(b&65535)+((((a>>>16)+(b>>>16)+((((a&65535)+(b&65535))>>>16)))|0)<<16)|0}function r(a,b){return a>>>b|a<<32-b}function T(a,b,c,d,e,f){return L(r(a=L(L(a,b),L(d,f)),e),c)}function q(a,b,c,d,e,f,g){return T(b&c|~b&d,a,b,e,f,g)}function p(a,b,c,d,e,f,g){return T(b&d|c&~d,a,b,e,f,g)}function n(a,b,c,d,e,f,g){return T(b^c^d,a,b,e,f,g)}function m(a,b,c,d,e,f,g){return T(c^(b|~d),a,b,e,f,g)}var i,o,t,u,a=function(s){var a,e=s.length,n=[],t=8*e,i=0;for(a=0;a<e;a++)n[a>>2]|=(255&s.charCodeAt(a))<<24-8*(a%4);n[t>>5]|=128<<24-t%32;n[15+(t+64>>9<<4)]=t;return n},f=a(s),h=1732584193,g=-271733879,b=-1732584194,c=271733878;for(i=0;i<f.length;i+=16){o=h;t=g;u=b;var v=c;h=q(h,g,b,c,f[i],7,-680876936);c=q(c,h,g,b,f[i+1],12,-389564586);b=q(b,c,h,g,f[i+2],17,606105819);g=q(g,b,c,h,f[i+3],22,-1044525330);h=q(h,g,b,c,f[i+4],7,-176418897);c=q(c,h,g,b,f[i+5],12,1200080426);b=q(b,c,h,g,f[i+6],17,-1473231341);g=q(g,b,c,h,f[i+7],22,-45705983);h=q(h,g,b,c,f[i+8],7,1770035416);c=q(c,h,g,b,f[i+9],12,-1958414417);b=q(b,c,h,g,f[i+10],17,-42063);g=q(g,b,c,h,f[i+11],22,-1990404162);h=q(h,g,b,c,f[i+12],7,1804603682);c=q(c,h,g,b,f[i+13],12,-40341101);b=q(b,c,h,g,f[i+14],17,-1502002290);g=q(g,b,c,h,f[i+15],22,1236535329);h=p(h,g,b,c,f[i+1],5,-165796510);c=p(c,h,g,b,f[i+6],9,-1069501632);b=p(b,c,h,g,f[i+11],14,643717713);g=p(g,b,c,h,f[i],20,-373897302);h=p(h,g,b,c,f[i+5],5,-701558691);c=p(c,h,g,b,f[i+10],9,38016083);b=p(b,c,h,g,f[i+15],14,-660478335);g=p(g,b,c,h,f[i+4],20,-405537848);h=p(h,g,b,c,f[i+9],5,568446438);c=p(c,h,g,b,f[i+14],9,-1019803690);b=p(b,c,h,g,f[i+3],14,-187363961);g=p(g,b,c,h,f[i+8],20,1163531501);h=p(h,g,b,c,f[i+13],5,-1444681467);c=p(c,h,g,b,f[i+2],9,-51403784);b=p(b,c,h,g,f[i+7],14,1735328473);g=p(g,b,c,h,f[i+12],20,-1926607734);h=n(h,g,b,c,f[i+5],4,-378558);c=n(c,h,g,b,f[i+8],11,-2022574463);b=n(b,c,h,g,f[i+11],16,1839030562);g=n(g,b,c,h,f[i+14],23,-35309556);h=n(h,g,b,c,f[i+1],4,-1530992060);c=n(c,h,g,b,f[i+4],11,1272893353);b=n(b,c,h,g,f[i+7],16,-155497632);g=n(g,b,c,h,f[i+10],23,-1094730640);h=n(h,g,b,c,f[i+13],4,681279174);c=n(c,h,g,b,f[i],11,-358537222);b=n(b,c,h,g,f[i+3],16,-722521979);g=n(g,b,c,h,f[i+6],23,76029189);h=n(h,g,b,c,f[i+9],4,-640364487);c=n(c,h,g,b,f[i+12],11,-421815835);b=n(b,c,h,g,f[i+15],16,530742520);g=n(g,b,c,h,f[i+2],23,-995338651);h=m(h,g,b,c,f[i],6,-198630844);c=m(c,h,g,b,f[i+7],10,1126891415);b=m(b,c,h,g,f[i+14],15,-1416354905);g=m(g,b,c,h,f[i+5],21,-57434055);h=m(h,g,b,c,f[i+12],6,1700485571);c=m(c,h,g,b,f[i+3],10,-1894986606);b=m(b,c,h,g,f[i+10],15,-1051523);g=m(g,b,c,h,f[i+1],21,-2054922799);h=m(h,g,b,c,f[i+8],6,1873313359);c=m(c,h,g,b,f[i+15],10,-30611744);b=m(b,c,h,g,f[i+6],15,-1560198380);g=m(g,b,c,h,f[i+13],21,1309151649);h=m(h,g,b,c,f[i+4],6,-145523070);c=m(c,h,g,b,f[i+11],10,-1120210379);b=m(b,c,h,g,f[i+2],15,718787259);g=m(g,b,c,h,f[i+9],21,-343485551);h=L(h,o);g=L(g,t);b=L(b,u);c=L(c,v)}var x=\'\';for(var j=0;j<4;j++){var k=arguments[0]==\'big\'?[h,g,b,c][j]:({0:h,1:g,2:b,3:c}[j]);for(var l=0;l<32;l+=8)x+=(\'0\'+(k>>>l&255).toString(16)).slice(-2)}return x}',
  'function doLogin(){document.sendin.username.value=document.login.username.value;document.sendin.password.value=hexMD5(\'$(chap-id)\'+document.login.password.value+\'$(chap-challenge)\');document.sendin.submit();return false}',
  '<\/script>',
].join('\n')

const CHAP_HIDDEN_FORM = [
  '$(if chap-id)',
  '<form name="sendin" action="$(link-login-only)" method="post" style="display:none">',
  '  <input type="hidden" name="username" />',
  '  <input type="hidden" name="password" />',
  '  <input type="hidden" name="dst" value="$(link-orig)" />',
  '  <input type="hidden" name="popup" value="true" />',
  '<\/form>',
  CHAP_SCRIPT,
  '$(endif)',
].join('\n')

// ── Template: Minimal ────────────────────────────────────────────────────────

export const MINIMAL_TEMPLATE = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8" />',
  '<meta http-equiv="pragma" content="no-cache" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '<style>',
  '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
  'body {',
  '  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;',
  '  min-height: 100vh;',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  padding: 1.25rem;',
  '  background: #e5e7eb;',
  '}',
  '.card {',
  '  width: 100%; max-width: 380px;',
  '  background: #fafafa;',
  '  border: 1px solid #d4d4d8;',
  '  padding: 2.25rem 2rem;',
  '}',
  '.brand { display: flex; align-items: center; gap: .5rem; margin-bottom: 1rem; }',
  '.brand-pill {',
  '  background: #111827; color: #fff;',
  '  font-size: .65rem; font-weight: 800; letter-spacing: .06em; text-transform: uppercase;',
  '  padding: .2rem .55rem;',
  '}',
  '.brand-name { font-size: .8rem; font-weight: 600; color: #111827; letter-spacing: -.01em; }',
  'h1 { font-size: 1.375rem; font-weight: 800; color: #111827; letter-spacing: -.03em; margin-bottom: .35rem; }',
  '.sub { font-size: .75rem; color: #6b7280; margin-bottom: 1.5rem; }',
  '.field { margin-bottom: 1rem; }',
  '.field label { display: block; font-size: .7rem; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; color: #6b7280; margin-bottom: .35rem; }',
  'input[type="text"], input[type="password"] {',
  '  width: 100%; padding: .7rem 1rem; font-size: .9rem; font-family: inherit;',
  '  background: #fff; border: 1px solid #d4d4d8;',
  '  color: #111827; outline: none; transition: border-color .15s;',
  '}',
  'input[type="text"]:focus, input[type="password"]:focus { border-color: #111827; }',
  '.err { font-size: .75rem; color: #dc2626; margin-bottom: 1rem; text-align: center; }',
  'button[type="submit"] {',
  '  width: 100%; margin-top: .5rem; padding: .8rem 1rem;',
  '  background: #111827; color: #fff; border: none;',
  '  font-size: .875rem; font-weight: 700; font-family: inherit; cursor: pointer;',
  '  letter-spacing: .01em; transition: filter .15s;',
  '}',
  'button[type="submit"]:hover { filter: brightness(1.3); }',
  '.footer { font-size: .6rem; color: #a1a1aa; text-align: center; margin-top: 1.5rem; }',
  '<\/style>',
  '<\/head>',
  '<body>',
  CHAP_HIDDEN_FORM,
  '<div class="card">',
  '  <div class="brand">',
  '    <span class="brand-pill">WiFi<\/span>',
  '    <span class="brand-name">__TITLE__<\/span>',
  '  <\/div>',
  '  <p class="sub">__SUBTITLE__<\/p>',
  '  $(if error)<p class="err">$(error)<\/p>$(endif)',
  '  <form name="login" action="$(link-login-only)" method="post" $(if chap-id)onsubmit="return doLogin()"$(endif)>',
  '    <input type="hidden" name="dst" value="$(link-orig)" />',
  '    <input type="hidden" name="popup" value="true" />',
  '    <div class="field"><label for="u">Username<\/label><input id="u" type="text" name="username" value="$(username)" placeholder="Enter username" autocomplete="username" /><\/div>',
  '    <div class="field"><label for="p">Password<\/label><input id="p" type="password" name="password" placeholder="Enter password" autocomplete="current-password" /><\/div>',
  '    <button type="submit">Connect &rarr;<\/button>',
  '  <\/form>',
  '  <p class="footer">Powered by Pikro<\/p>',
  '<\/div>',
  '<\/body>',
  '<\/html>',
].join('\n')

// ── Template: Wave ───────────────────────────────────────────────────────────
// Light card centered on a soft background, decorative wavy accent line under
// the heading.

export const WAVE_TEMPLATE = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8" />',
  '<meta http-equiv="pragma" content="no-cache" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '<style>',
  '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
  'body {',
  '  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;',
  '  min-height: 100vh; display: flex; align-items: center; justify-content: center;',
  '  padding: 1.25rem; background: #f6f5fb;',
  '}',
  '.card {',
  '  width: 100%; max-width: 380px; background: #fff; border-radius: 24px;',
  '  padding: 2.5rem 2rem 2rem; box-shadow: 0 1px 2px rgba(0,0,0,.04), 0 12px 32px rgba(0,0,0,.06);',
  '}',
  'h1 { font-size: 1.5rem; font-weight: 800; color: #111827; letter-spacing: -.03em; text-align: center; }',
  '.wave { display: block; margin: .6rem auto 0; }',
  '.sub { font-size: .8rem; color: #9ca3af; text-align: center; margin: .75rem 0 1.75rem; }',
  '.field { margin-bottom: 1rem; }',
  '.field label { display: block; font-size: .7rem; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; color: #9ca3af; margin-bottom: .35rem; }',
  'input[type="text"], input[type="password"] {',
  '  width: 100%; padding: .7rem 1rem; font-size: .9rem; font-family: inherit;',
  '  background: #f9fafb; border: 1.5px solid #eef0f2; border-radius: 12px;',
  '  color: #111827; outline: none; transition: border-color .15s, background .15s; -webkit-appearance: none;',
  '}',
  'input[type="text"]:focus, input[type="password"]:focus { border-color: #7c3aed; background: #fff; }',
  '.err { font-size: .75rem; color: #dc2626; background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: .6rem .875rem; margin-bottom: 1rem; text-align: center; }',
  'button[type="submit"] {',
  '  width: 100%; margin-top: .5rem; padding: .8rem 1rem;',
  '  background: #7c3aed; color: #fff; border: none; border-radius: 999px;',
  '  font-size: .875rem; font-weight: 700; font-family: inherit; cursor: pointer;',
  '  letter-spacing: .01em; transition: filter .15s;',
  '}',
  'button[type="submit"]:hover { filter: brightness(1.1); }',
  '.footer { font-size: .6rem; color: #d1d5db; text-align: center; margin-top: 1.5rem; }',
  '<\/style>',
  '<\/head>',
  '<body>',
  CHAP_HIDDEN_FORM,
  '<div class="card">',
  '  <h1>__TITLE__<\/h1>',
  '  <svg class="wave" width="72" height="10" viewBox="0 0 72 10" fill="none">',
  '    <path d="M2 6c4-6 8-6 12 0s8 6 12 0 8-6 12 0 8 6 12 0 8-6 12 0" stroke="#7c3aed" stroke-width="2" stroke-linecap="round" fill="none"/>',
  '  <\/svg>',
  '  <p class="sub">__SUBTITLE__<\/p>',
  '  $(if error)<p class="err">$(error)<\/p>$(endif)',
  '  <form name="login" action="$(link-login-only)" method="post" $(if chap-id)onsubmit="return doLogin()"$(endif)>',
  '    <input type="hidden" name="dst" value="$(link-orig)" />',
  '    <input type="hidden" name="popup" value="true" />',
  '    <div class="field"><label for="u">Username<\/label><input id="u" type="text" name="username" value="$(username)" placeholder="Enter username" autocomplete="username" /><\/div>',
  '    <div class="field"><label for="p">Password<\/label><input id="p" type="password" name="password" placeholder="Enter password" autocomplete="current-password" /><\/div>',
  '    <button type="submit">Connect &rarr;<\/button>',
  '  <\/form>',
  '  <p class="footer">Powered by Pikro<\/p>',
  '<\/div>',
  '<\/body>',
  '<\/html>',
].join('\n')

// ── Template: Card ───────────────────────────────────────────────────────────
// Classic centered card on a plain light background — traditional
// captive-portal "Login Form" look, kept simple with no colored fill.

export const CARD_TEMPLATE = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8" />',
  '<meta http-equiv="pragma" content="no-cache" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '<style>',
  '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
  'body {',
  '  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;',
  '  min-height: 100vh; display: flex; align-items: center; justify-content: center;',
  '  padding: 1.25rem; background: #f3f4f6;',
  '}',
  '.card { width: 100%; max-width: 340px; background: #fff; border: 1px solid #e5e7eb; border-radius: 10px; overflow: hidden; }',
  '.header { padding: 1.5rem 1.5rem 0; }',
  '.header h1 { font-size: 1.05rem; font-weight: 700; color: #111827; text-align: center; }',
  '.body { padding: 1.5rem; }',
  '.sub { font-size: .75rem; color: #9ca3af; text-align: center; margin-bottom: 1.5rem; }',
  '.err { font-size: .75rem; color: #dc2626; background: #fef2f2; border: 1px solid #fecaca; border-radius: 6px; padding: .6rem .875rem; margin-bottom: 1rem; text-align: center; }',
  '.field { margin-bottom: 1rem; }',
  '.field label { display: block; font-size: .72rem; font-weight: 600; color: #6b7280; margin-bottom: .3rem; }',
  'input[type="text"], input[type="password"] {',
  '  width: 100%; padding: .6rem .8rem; font-size: .875rem; font-family: inherit;',
  '  border: 1px solid #d1d5db; border-radius: 4px; background: #fff; color: #111827;',
  '  outline: none; transition: border-color .15s, box-shadow .15s;',
  '}',
  'input[type="text"]:focus, input[type="password"]:focus { border-color: #2563eb; box-shadow: 0 0 0 3px rgba(37,99,235,.15); }',
  'button[type="submit"] {',
  '  display: block; width: 100%; margin-top: .5rem; padding: .65rem 1rem;',
  '  background: #2563eb; color: #fff; border: none; border-radius: 4px;',
  '  font-size: .875rem; font-weight: 600; font-family: inherit; cursor: pointer; transition: filter .15s;',
  '}',
  'button[type="submit"]:hover { filter: brightness(1.1); }',
  '.footer { font-size: .65rem; color: #d1d5db; text-align: center; margin-top: 1.25rem; }',
  '<\/style>',
  '<\/head>',
  '<body>',
  CHAP_HIDDEN_FORM,
  '<div class="card">',
  '  <div class="header"><h1>__TITLE__<\/h1><\/div>',
  '  <div class="body">',
  '    <p class="sub">__SUBTITLE__<\/p>',
  '    $(if error)<p class="err">$(error)<\/p>$(endif)',
  '    <form name="login" action="$(link-login-only)" method="post" $(if chap-id)onsubmit="return doLogin()"$(endif)>',
  '      <input type="hidden" name="dst" value="$(link-orig)" />',
  '      <input type="hidden" name="popup" value="true" />',
  '      <div class="field"><label for="u">Username<\/label><input id="u" type="text" name="username" value="$(username)" placeholder="Enter username" autocomplete="username" /><\/div>',
  '      <div class="field"><label for="p">Password<\/label><input id="p" type="password" name="password" placeholder="Enter password" autocomplete="current-password" /><\/div>',
  '      <button type="submit">Login<\/button>',
  '    <\/form>',
  '    <p class="footer">Powered by Pikro<\/p>',
  '  <\/div>',
  '<\/div>',
  '<\/body>',
  '<\/html>',
].join('\n')
