// Minified Paul Johnston reference MD5 impl (the same one MikroTik's own
// stock hotspot templates use)
const CHAP_SCRIPT = [
  '<script>',
  'function safe_add(f,i){var n=(65535&f)+(65535&i);return(f>>16)+(i>>16)+(n>>16)<<16|65535&n}function rol(f,i){return f<<i|f>>>32-i}function cmn(f,i,n,h,r,g){return safe_add(rol(safe_add(safe_add(i,f),safe_add(h,g)),r),n)}function ff(f,i,n,h,r,g,e){return cmn(i&n|~i&h,f,i,r,g,e)}function gg(f,i,n,h,r,g,e){return cmn(i&h|n&~h,f,i,r,g,e)}function hh(f,i,n,h,r,g,e){return cmn(i^n^h,f,i,r,g,e)}function ii(f,i,n,h,r,g,e){return cmn(n^(i|~h),f,i,r,g,e)}function coreMD5(f){for(var i=1732584193,n=-271733879,h=-1732584194,r=271733878,g=0;g<f.length;g+=16){var e=i,t=n,a=h,c=r;i=ff(i,n,h,r,f[g+0],7,-680876936),r=ff(r,i,n,h,f[g+1],12,-389564586),h=ff(h,r,i,n,f[g+2],17,606105819),n=ff(n,h,r,i,f[g+3],22,-1044525330),i=ff(i,n,h,r,f[g+4],7,-176418897),r=ff(r,i,n,h,f[g+5],12,1200080426),h=ff(h,r,i,n,f[g+6],17,-1473231341),n=ff(n,h,r,i,f[g+7],22,-45705983),i=ff(i,n,h,r,f[g+8],7,1770035416),r=ff(r,i,n,h,f[g+9],12,-1958414417),h=ff(h,r,i,n,f[g+10],17,-42063),n=ff(n,h,r,i,f[g+11],22,-1990404162),i=ff(i,n,h,r,f[g+12],7,1804603682),r=ff(r,i,n,h,f[g+13],12,-40341101),h=ff(h,r,i,n,f[g+14],17,-1502002290),i=gg(i,n=ff(n,h,r,i,f[g+15],22,1236535329),h,r,f[g+1],5,-165796510),r=gg(r,i,n,h,f[g+6],9,-1069501632),h=gg(h,r,i,n,f[g+11],14,643717713),n=gg(n,h,r,i,f[g+0],20,-373897302),i=gg(i,n,h,r,f[g+5],5,-701558691),r=gg(r,i,n,h,f[g+10],9,38016083),h=gg(h,r,i,n,f[g+15],14,-660478335),n=gg(n,h,r,i,f[g+4],20,-405537848),i=gg(i,n,h,r,f[g+9],5,568446438),r=gg(r,i,n,h,f[g+14],9,-1019803690),h=gg(h,r,i,n,f[g+3],14,-187363961),n=gg(n,h,r,i,f[g+8],20,1163531501),i=gg(i,n,h,r,f[g+13],5,-1444681467),r=gg(r,i,n,h,f[g+2],9,-51403784),h=gg(h,r,i,n,f[g+7],14,1735328473),i=hh(i,n=gg(n,h,r,i,f[g+12],20,-1926607734),h,r,f[g+5],4,-378558),r=hh(r,i,n,h,f[g+8],11,-2022574463),h=hh(h,r,i,n,f[g+11],16,1839030562),n=hh(n,h,r,i,f[g+14],23,-35309556),i=hh(i,n,h,r,f[g+1],4,-1530992060),r=hh(r,i,n,h,f[g+4],11,1272893353),h=hh(h,r,i,n,f[g+7],16,-155497632),n=hh(n,h,r,i,f[g+10],23,-1094730640),i=hh(i,n,h,r,f[g+13],4,681279174),r=hh(r,i,n,h,f[g+0],11,-358537222),h=hh(h,r,i,n,f[g+3],16,-722521979),n=hh(n,h,r,i,f[g+6],23,76029189),i=hh(i,n,h,r,f[g+9],4,-640364487),r=hh(r,i,n,h,f[g+12],11,-421815835),h=hh(h,r,i,n,f[g+15],16,530742520),i=ii(i,n=hh(n,h,r,i,f[g+2],23,-995338651),h,r,f[g+0],6,-198630844),r=ii(r,i,n,h,f[g+7],10,1126891415),h=ii(h,r,i,n,f[g+14],15,-1416354905),n=ii(n,h,r,i,f[g+5],21,-57434055),i=ii(i,n,h,r,f[g+12],6,1700485571),r=ii(r,i,n,h,f[g+3],10,-1894986606),h=ii(h,r,i,n,f[g+10],15,-1051523),n=ii(n,h,r,i,f[g+1],21,-2054922799),i=ii(i,n,h,r,f[g+8],6,1873313359),r=ii(r,i,n,h,f[g+15],10,-30611744),h=ii(h,r,i,n,f[g+6],15,-1560198380),n=ii(n,h,r,i,f[g+13],21,1309151649),i=ii(i,n,h,r,f[g+4],6,-145523070),r=ii(r,i,n,h,f[g+11],10,-1120210379),h=ii(h,r,i,n,f[g+2],15,718787259),n=ii(n,h,r,i,f[g+9],21,-343485551),i=safe_add(i,e),n=safe_add(n,t),h=safe_add(h,a),r=safe_add(r,c)}return[i,n,h,r]}function binl2hex(f){for(var i="0123456789abcdef",n="",h=0;h<4*f.length;h++)n+=i.charAt(f[h>>2]>>h%4*8+4&15)+i.charAt(f[h>>2]>>h%4*8&15);return n}function str2binl(f){for(var i=1+(f.length+8>>6),n=new Array(16*i),h=0;h<16*i;h++)n[h]=0;for(h=0;h<f.length;h++)n[h>>2]|=(255&f.charCodeAt(h))<<h%4*8;return n[h>>2]|=128<<h%4*8,n[16*i-2]=8*f.length,n}function hexMD5(f){return binl2hex(coreMD5(str2binl(f)))}',
  'function doLogin(){document.sendin.username.value=document.login.username.value;document.sendin.password.value=hexMD5(\'$(chap-id)\'+document.login.password.value+\'$(chap-challenge)\');document.sendin.submit();return false}',
  '<\/script>',
].join('\n')

const CHAP_HIDDEN_FORM = [
  '$(if chap-id)',
  '<form name="sendin" action="$(link-login-only)" method="post" style="display:none">',
  '  <input type="hidden" name="username" />',
  '  <input type="hidden" name="password" />',
  '  <input type="hidden" name="dst" value="$(link-orig)" />',
  '  <input type="hidden" name="popup" value="true" />',
  '<\/form>',
  CHAP_SCRIPT,
  '$(endif)',
].join('\n')

// ── Template: Minimal ────────────────────────────────────────────────────────

export const MINIMAL_TEMPLATE = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8" />',
  '<meta http-equiv="pragma" content="no-cache" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '<style>',
  '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
  'body {',
  '  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;',
  '  min-height: 100vh;',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  padding: 1.25rem;',
  '  background: #e5e7eb;',
  '}',
  '.card {',
  '  width: 100%; max-width: 380px;',
  '  background: #fafafa;',
  '  border: 1px solid #d4d4d8;',
  '  padding: 2.25rem 2rem;',
  '}',
  '.brand { display: flex; align-items: center; gap: .5rem; margin-bottom: 1rem; }',
  '.brand-pill {',
  '  background: #111827; color: #fff;',
  '  font-size: .65rem; font-weight: 800; letter-spacing: .06em; text-transform: uppercase;',
  '  padding: .2rem .55rem;',
  '}',
  '.brand-name { font-size: .8rem; font-weight: 600; color: #111827; letter-spacing: -.01em; }',
  'h1 { font-size: 1.375rem; font-weight: 800; color: #111827; letter-spacing: -.03em; margin-bottom: .35rem; }',
  '.sub { font-size: .75rem; color: #6b7280; margin-bottom: 1.5rem; }',
  '.field { margin-bottom: 1rem; }',
  '.field label { display: block; font-size: .7rem; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; color: #6b7280; margin-bottom: .35rem; }',
  'input[type="text"], input[type="password"] {',
  '  width: 100%; padding: .7rem 1rem; font-size: .9rem; font-family: inherit;',
  '  background: #fff; border: 1px solid #d4d4d8;',
  '  color: #111827; outline: none; transition: border-color .15s;',
  '}',
  'input[type="text"]:focus, input[type="password"]:focus { border-color: #111827; }',
  '.err { font-size: .75rem; color: #dc2626; margin-bottom: 1rem; text-align: center; }',
  'button[type="submit"] {',
  '  width: 100%; margin-top: .5rem; padding: .8rem 1rem;',
  '  background: #111827; color: #fff; border: none;',
  '  font-size: .875rem; font-weight: 700; font-family: inherit; cursor: pointer;',
  '  letter-spacing: .01em; transition: filter .15s;',
  '}',
  'button[type="submit"]:hover { filter: brightness(1.3); }',
  '.footer { font-size: .6rem; color: #a1a1aa; text-align: center; margin-top: 1.5rem; }',
  '<\/style>',
  '<\/head>',
  '<body>',
  CHAP_HIDDEN_FORM,
  '<div class="card">',
  '  <div class="brand">',
  '    <span class="brand-pill">WiFi<\/span>',
  '    <span class="brand-name">__TITLE__<\/span>',
  '  <\/div>',
  '  <p class="sub">__SUBTITLE__<\/p>',
  '  $(if error)<p class="err">$(error)<\/p>$(endif)',
  '  <form name="login" action="$(link-login-only)" method="post" $(if chap-id)onsubmit="return doLogin()"$(endif)>',
  '    <input type="hidden" name="dst" value="$(link-orig)" />',
  '    <input type="hidden" name="popup" value="true" />',
  '    <div class="field"><label for="u">Username<\/label><input id="u" type="text" name="username" value="$(username)" placeholder="Enter username" autocomplete="username" /><\/div>',
  '    <div class="field"><label for="p">Password<\/label><input id="p" type="password" name="password" placeholder="Enter password" autocomplete="current-password" /><\/div>',
  '    <button type="submit">Connect &rarr;<\/button>',
  '  <\/form>',
  '  <p class="footer">Powered by Pikro<\/p>',
  '<\/div>',
  '<\/body>',
  '<\/html>',
].join('\n')

// ── Template: Wave ───────────────────────────────────────────────────────────
// Light card centered on a soft background, decorative wavy accent line under
// the heading.

export const WAVE_TEMPLATE = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8" />',
  '<meta http-equiv="pragma" content="no-cache" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '<style>',
  '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
  'body {',
  '  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;',
  '  min-height: 100vh; display: flex; align-items: center; justify-content: center;',
  '  padding: 1.25rem; background: #f6f5fb;',
  '}',
  '.card {',
  '  width: 100%; max-width: 380px; background: #fff; border-radius: 24px;',
  '  padding: 2.5rem 2rem 2rem; box-shadow: 0 1px 2px rgba(0,0,0,.04), 0 12px 32px rgba(0,0,0,.06);',
  '}',
  'h1 { font-size: 1.5rem; font-weight: 800; color: #111827; letter-spacing: -.03em; text-align: center; }',
  '.wave { display: block; margin: .6rem auto 0; }',
  '.sub { font-size: .8rem; color: #9ca3af; text-align: center; margin: .75rem 0 1.75rem; }',
  '.field { margin-bottom: 1rem; }',
  '.field label { display: block; font-size: .7rem; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; color: #9ca3af; margin-bottom: .35rem; }',
  'input[type="text"], input[type="password"] {',
  '  width: 100%; padding: .7rem 1rem; font-size: .9rem; font-family: inherit;',
  '  background: #f9fafb; border: 1.5px solid #eef0f2; border-radius: 12px;',
  '  color: #111827; outline: none; transition: border-color .15s, background .15s; -webkit-appearance: none;',
  '}',
  'input[type="text"]:focus, input[type="password"]:focus { border-color: #7c3aed; background: #fff; }',
  '.err { font-size: .75rem; color: #dc2626; background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: .6rem .875rem; margin-bottom: 1rem; text-align: center; }',
  'button[type="submit"] {',
  '  width: 100%; margin-top: .5rem; padding: .8rem 1rem;',
  '  background: #7c3aed; color: #fff; border: none; border-radius: 999px;',
  '  font-size: .875rem; font-weight: 700; font-family: inherit; cursor: pointer;',
  '  letter-spacing: .01em; transition: filter .15s;',
  '}',
  'button[type="submit"]:hover { filter: brightness(1.1); }',
  '.footer { font-size: .6rem; color: #d1d5db; text-align: center; margin-top: 1.5rem; }',
  '<\/style>',
  '<\/head>',
  '<body>',
  CHAP_HIDDEN_FORM,
  '<div class="card">',
  '  <h1>__TITLE__<\/h1>',
  '  <svg class="wave" width="72" height="10" viewBox="0 0 72 10" fill="none">',
  '    <path d="M2 6c4-6 8-6 12 0s8 6 12 0 8-6 12 0 8 6 12 0 8-6 12 0" stroke="#7c3aed" stroke-width="2" stroke-linecap="round" fill="none"/>',
  '  <\/svg>',
  '  <p class="sub">__SUBTITLE__<\/p>',
  '  $(if error)<p class="err">$(error)<\/p>$(endif)',
  '  <form name="login" action="$(link-login-only)" method="post" $(if chap-id)onsubmit="return doLogin()"$(endif)>',
  '    <input type="hidden" name="dst" value="$(link-orig)" />',
  '    <input type="hidden" name="popup" value="true" />',
  '    <div class="field"><label for="u">Username<\/label><input id="u" type="text" name="username" value="$(username)" placeholder="Enter username" autocomplete="username" /><\/div>',
  '    <div class="field"><label for="p">Password<\/label><input id="p" type="password" name="password" placeholder="Enter password" autocomplete="current-password" /><\/div>',
  '    <button type="submit">Connect &rarr;<\/button>',
  '  <\/form>',
  '  <p class="footer">Powered by Pikro<\/p>',
  '<\/div>',
  '<\/body>',
  '<\/html>',
].join('\n')

// ── Template: Card ───────────────────────────────────────────────────────────
// Classic centered card on a plain light background — traditional
// captive-portal "Login Form" look, kept simple with no colored fill.

export const CARD_TEMPLATE = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8" />',
  '<meta http-equiv="pragma" content="no-cache" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '<style>',
  '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
  'body {',
  '  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;',
  '  min-height: 100vh; display: flex; align-items: center; justify-content: center;',
  '  padding: 1.25rem; background: #f3f4f6;',
  '}',
  '.card { width: 100%; max-width: 340px; background: #fff; border: 1px solid #e5e7eb; border-radius: 10px; overflow: hidden; }',
  '.header { padding: 1.5rem 1.5rem 0; }',
  '.header h1 { font-size: 1.05rem; font-weight: 700; color: #111827; text-align: center; }',
  '.body { padding: 1.5rem; }',
  '.sub { font-size: .75rem; color: #9ca3af; text-align: center; margin-bottom: 1.5rem; }',
  '.err { font-size: .75rem; color: #dc2626; background: #fef2f2; border: 1px solid #fecaca; border-radius: 6px; padding: .6rem .875rem; margin-bottom: 1rem; text-align: center; }',
  '.field { margin-bottom: 1rem; }',
  '.field label { display: block; font-size: .72rem; font-weight: 600; color: #6b7280; margin-bottom: .3rem; }',
  'input[type="text"], input[type="password"] {',
  '  width: 100%; padding: .6rem .8rem; font-size: .875rem; font-family: inherit;',
  '  border: 1px solid #d1d5db; border-radius: 4px; background: #fff; color: #111827;',
  '  outline: none; transition: border-color .15s, box-shadow .15s;',
  '}',
  'input[type="text"]:focus, input[type="password"]:focus { border-color: #2563eb; box-shadow: 0 0 0 3px rgba(37,99,235,.15); }',
  'button[type="submit"] {',
  '  display: block; width: 100%; margin-top: .5rem; padding: .65rem 1rem;',
  '  background: #2563eb; color: #fff; border: none; border-radius: 4px;',
  '  font-size: .875rem; font-weight: 600; font-family: inherit; cursor: pointer; transition: filter .15s;',
  '}',
  'button[type="submit"]:hover { filter: brightness(1.1); }',
  '.footer { font-size: .65rem; color: #d1d5db; text-align: center; margin-top: 1.25rem; }',
  '<\/style>',
  '<\/head>',
  '<body>',
  CHAP_HIDDEN_FORM,
  '<div class="card">',
  '  <div class="header"><h1>__TITLE__<\/h1><\/div>',
  '  <div class="body">',
  '    <p class="sub">__SUBTITLE__<\/p>',
  '    $(if error)<p class="err">$(error)<\/p>$(endif)',
  '    <form name="login" action="$(link-login-only)" method="post" $(if chap-id)onsubmit="return doLogin()"$(endif)>',
  '      <input type="hidden" name="dst" value="$(link-orig)" />',
  '      <input type="hidden" name="popup" value="true" />',
  '      <div class="field"><label for="u">Username<\/label><input id="u" type="text" name="username" value="$(username)" placeholder="Enter username" autocomplete="username" /><\/div>',
  '      <div class="field"><label for="p">Password<\/label><input id="p" type="password" name="password" placeholder="Enter password" autocomplete="current-password" /><\/div>',
  '      <button type="submit">Login<\/button>',
  '    <\/form>',
  '    <p class="footer">Powered by Pikro<\/p>',
  '  <\/div>',
  '<\/div>',
  '<\/body>',
  '<\/html>',
].join('\n')
